base_url = 'https://reports.sandbox.experience.com'
login_base_url = 'https://api.sandbox.experience.com'
access_token = "eyJhbGciOiJIUzI1NiJ9.eyJzZXNzaW9uX2tleSI6Ik9sNU9YWER0QTlXcGVZSnpFRmY5ai9KUm5xTitjS01PODBJS1R6WXpXV1YyVktLNXlaM0FHbDFvMzhkVGlqa3J1SER3N2tvcEo5UHM1MWpjIiwiZXhwaXJlc19hdCI6IjIwMjEtMDQtMDIgMDg6NDM6NTAgVVRDIn0.yyeZo5a1lR4eFwqhejq2FFLCPYJfLN1LZMlO2zPRLew"
